= Camel Quarkus Examples

The idea of this repository is to make available, quickly and objectively, some proofs of concept and demonstrations of camel quarkus so that we can apply them to our customers. We ask that each usage case occupies a specific folder and that a devfile is created (stored in the devfile folder) in order to organize and achieve a clean development environment for each application.

Everyone is invited to collaborate, enjoy!

== Contents

1. camel-quarkus-kafka-api-mongo - An API example with Camel Quarkus whose POST method sends the records to kafka and the GET method fetches the records from a mongoDB. 

2. camel-quarkus-kafka-consumer-mongo - An example consumer subscribing to a kafka topic and when messages arrive in that topic it saves the topic messages in mongoDB.

3. camel-quarkus-artemis-consumer - An example of a consumer subscribing to an artemis(AMQ broker) topic(raw) and queuing to another topic(processed).

4. camel-quarkus-ws-to-event - An example of websocket receiving a json payload, then queuing in a topic(raw) from artemis(AMQ Broker) and a kafka topic(raw too) using wiretap.

5. camel-quarkus-ws-to-event-artemis - An example of websocket receiving a json payload, then queuing in a topic(raw) from artemis(AMQ Broker).

6. camel-quarkus-kafka - An example of a consumer subscribing to an kafka topic(raw) and queuing to another topic(processed).

7. camel-quarkus-oracle - An example of API with oracle 19c JDBC connection

8. camel-quarkus-infinispan - An example of API proxy using cache from datagrid. This example uses circuit breaker and choice patterns and consumes camel-quarkus-oracle API.

== Useful Links

https://code.quarkus.redhat.com/ - Application Generator

https://developers.redhat.com/developer-sandbox - Developer Sandbox of CodeReady Workspaces

https://github.com/apache/camel-quarkus-examples - Simple Examples of power of Camel Quarkus
