#
# Kafka Configuration
#
quarkus.openshift.env.vars.kafka-bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-kafka-bootstrap-kafka.apps.cluster-jvtsx.jvtsx.sandbox808.opentlc.com:443}
quarkus.openshift.env.vars.kafka-topic=${KAFKA_TOPIC:events}
quarkus.openshift.env.vars.kafka-group-id=${KAFKA_GROUP_ID:camel-quarkus-kafka-s3-consumer}
quarkus.openshift.env.vars.kafka-consumer-max-poll-records=${KAFKA_CONSUMER_MAX_POLL_RECORDS:100000}
quarkus.openshift.env.vars.kafka-consumer-auto-commit-enable=${KAFKA_CONSUMER_AUTO_COMMIT_ENABLE:true}
quarkus.openshift.env.vars.kafka-consumer-fetch-min-bytes=${KAFKA_CONSUMER_FETCH_MIN_BYTES:1024}
quarkus.openshift.env.vars.kafka-consumer-fetch-wait-max-ms=${KAFKA_CONSUMER_FETCH_WAIT_MAX_MS:1}
quarkus.openshift.env.vars.kafka-consumer-fetch-max-bytes=${KAFKA_CONSUMER_FETCH_MAX_BYTES:26214400}
quarkus.openshift.env.vars.kafka-consumer-security-protocol=${KAFKA_CONSUMER_SECURITY_PROTOCOL:SASL_SSL}
quarkus.openshift.env.vars.kafka-consumer-ssl-truststore-location=${KAFKA_CONSUMER_TRUSTSTORE_LOCATION:/etc/security/truststore/truststore.jks}
quarkus.openshift.env.vars.kafka-consumer-ssl-truststore-password=${KAFKA_CONSUMER_TRUSTSTORE_PASSWORD:redhat}
quarkus.openshift.env.vars.kafka-consumer-sasl-mechanism=${KAFKA_CONSUMER_SASL_MECHANISM:SCRAM-SHA-512}
quarkus.openshift.env.vars.kafka-consumer-sasl-jaas-config=${KAFKA_CONSUMER_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username=redhat-user password=redhat123;}
quarkus.openshift.env.vars.kafka-producer-compression-codec=${KAFKA_PRODUCER_COMPRESSION_CODEC:none}
quarkus.openshift.env.vars.kafka-producer-required-acks=${KAFKA_PRODUCER_REQUIRED_ACKS:0}
quarkus.openshift.env.vars.kafka-producer-buffer-memory-size=${KAFKA_PRODUCER_BUFFER_MEMORY_SIZE:63554432}
quarkus.openshift.env.vars.kafka-producer-linger-ms=${KAFKA_PRODUCER_LINGER_MS:1}
quarkus.openshift.env.vars.kafka-producer-batch-size=${KAFKA_PRODUCER_BATCH_SIZE:16384}
quarkus.openshift.env.vars.kafka-producer-security-protocol=${KAFKA_PRODUCER_SECURITY_PROTOCOL:SASL_SSL}
quarkus.openshift.env.vars.kafka-producer-ssl-truststore-location=${KAFKA_PRODUCER_TRUSTSTORE_LOCATION:/etc/security/truststore/truststore.jks}
quarkus.openshift.env.vars.kafka-producer-ssl-truststore-password=${KAFKA_PRODUCER_TRUSTSTORE_PASSWORD:redhat}
quarkus.openshift.env.vars.kafka-producer-sasl-mechanism=${KAFKA_PRODUCER_SASL_MECHANISM:SCRAM-SHA-512}
quarkus.openshift.env.vars.kafka-producer-sasl-jaas-config=${KAFKA_PRODUCER_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username=redhat-user password=redhat123;}
quarkus.openshift.secret-volumes.truststore-secret.secret-name=truststore-secret
quarkus.openshift.secret-volumes.truststore-secret.default-mode=420
quarkus.openshift.mounts.truststore-secret.path=/etc/security/truststore

#
# Openshift
#
quarkus.camel.enabled=true
quarkus.kubernetes-client.trust-certs=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-17
quarkus.openshift.route.expose=true
quarkus.openshift.deploy=true