loggingLevel=info
loggingColor=true
loggingJson=false
camel.jbang.localKameletDir=file\:.
camel.main.routesReloadEnabled=true
camel.main.shutdownTimeout=5
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.6.0
camel.jbang.springBootVersion=3.2.5
camel.jbang.quarkusVersion=3.10.0
camel.jbang.kameletsVersion=4.6.0
camel.main.name=CamelJBang
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.6.0
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.6.0
dependency=mvn\:org.apache.camel\:camel-rest\:4.6.0
dependency=mvn\:org.apache.camel\:camel-rest-openapi\:4.6.0
