package br.com.solarbr.opshml.apps.kafka_soap_api_dev_ri_0_solar_core_apis_dev.kafka;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-27T10:57:04.450-03:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "KafkaPixService",
                  wsdlLocation = "file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl",
                  targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka")
public class KafkaPixService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", "KafkaPixService");
    public final static QName SendPixPort = new QName("http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", "SendPixPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KafkaPixService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KafkaPixService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KafkaPixService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KafkaPixService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KafkaPixService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KafkaPixService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KafkaPixService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KafkaPortType
     */
    @WebEndpoint(name = "SendPixPort")
    public KafkaPortType getSendPixPort() {
        return super.getPort(SendPixPort, KafkaPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KafkaPortType
     */
    @WebEndpoint(name = "SendPixPort")
    public KafkaPortType getSendPixPort(WebServiceFeature... features) {
        return super.getPort(SendPixPort, KafkaPortType.class, features);
    }

}
