package br.com.solarbr.opshml.apps.kafka_soap_api_dev_ri_0_solar_core_apis_dev.kafka;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-27T10:57:04.437-03:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "KafkaBoletoService",
                  wsdlLocation = "file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl",
                  targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka")
public class KafkaBoletoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", "KafkaBoletoService");
    public final static QName SendBoletoPort = new QName("http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", "SendBoletoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KafkaBoletoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/omelo/Repos/camel-quarkus-examples2/camel-quarkus-soap-kafka/src/main/resources/wsdl/invoice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KafkaBoletoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KafkaBoletoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KafkaBoletoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KafkaBoletoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KafkaBoletoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KafkaBoletoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns KafkaPortType
     */
    @WebEndpoint(name = "SendBoletoPort")
    public KafkaPortType getSendBoletoPort() {
        return super.getPort(SendBoletoPort, KafkaPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KafkaPortType
     */
    @WebEndpoint(name = "SendBoletoPort")
    public KafkaPortType getSendBoletoPort(WebServiceFeature... features) {
        return super.getPort(SendBoletoPort, KafkaPortType.class, features);
    }

}
