package br.com.solarbr.opshml.apps.kafka_soap_api_dev_ri_0_solar_core_apis_dev.kafka;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-27T10:57:04.431-03:00
 * Generated source version: 3.5.5
 *
 */
@WebService(
    targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka",
    name = "KafkaPortType"
)
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface KafkaPortType {

    @WebMethod(operationName = "SendBoleto")
    @WebResult(name = "PixResponse", targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", partName = "parameters")
    public PixResponse sendBoleto(

        @WebParam(partName = "parameters", name = "BoletoRequest", targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka")
        BoletoRequest parameters
    );

    @WebMethod(operationName = "SendPix", action = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka/SendPix")
    @WebResult(name = "PixResponse", targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka", partName = "parameters")
    public PixResponse sendPix(

        @WebParam(partName = "parameters", name = "PixRequest", targetNamespace = "http://kafka-soap-api-dev-ri-0-solar-core-apis-dev.apps.opshml.solarbr.com.br/kafka")
        PixRequest parameters
    );
}
